
const documentationData = [
    {
        category: "Core Serialization",
        id: "ConvertToRaw",
        signature: "Rawmeleon.ConvertToRaw(sentence, x, y, z, targetInstance)",
        description: "Packages custom layout strings alongside positional floats and standard geometric BasePart instances into an aligned sequential buffer stream.",
        example: `<span class="keyword">local</span> packet = Rawmeleon.ConvertToRaw(<span class="string">"Update position"</span>, <span class="number">102.5</span>, <span class="number">14.0</span>, <span class="number">-45.2</span>, workspace.Part)`,
        params: [
            { name: "sentence", type: "string", desc: "Text data layout up to 65,535 bytes in size." },
            { name: "x / y / z", type: "number", desc: "32-bit floating point coordinate updates." },
            { name: "targetInstance", type: "Instance", desc: "Target reference containing Name, Transparency, Collisions, and Color arrays." }
        ]
    },
    {
        category: "Core Serialization",
        id: "DecodeRaw",
        signature: "Rawmeleon.DecodeRaw(b)",
        description: "Parses an active data buffer stream generated by .ConvertToRaw back into structured dictionary values.",
        example: `<span class="keyword">local</span> data = Rawmeleon.DecodeRaw(packet)`,
        params: [
            { name: "b", type: "buffer", desc: "The packed binary buffer to read from." }
        ]
    },
    {
        category: "Core Serialization",
        id: "ReturnRawData",
        signature: "Rawmeleon.ReturnRawData(b)",
        description: "Inspects an active buffer array and serializes its sequence pointers directly into a space-separated string of hexadecimals.",
        example: `<span class="keyword">print</span>(Rawmeleon.ReturnRawData(packet)) <span class="comment">-- Outputs: 0F 02 A3 4F CC ...</span>`,
        params: [
            { name: "b", type: "buffer", desc: "Target buffer array to scan." }
        ]
    },
        {
        category: "Environment Telemetry",
        id: "GetPlayerRawData",
        signature: "Rawmeleon.GetPlayerRawData(player)",
        description: "Packs basic data layout identities belonging to a Player instance, implementing a 64-bit precise allocation register block to prevent numeric corruption on modern global UserIds.",
        example: `<span class="keyword">local</span> accountBuffer = Rawmeleon.GetPlayerRawData(game.Players.LocalPlayer)`,
        params: [
            { name: "player", type: "Player", desc: "The target player object to fetch data from." }
        ]
    },
    {
        category: "Environment Telemetry",
        id: "GetPlayerPropertiesRaw",
        signature: "Rawmeleon.GetPlayerPropertiesRaw(player)",
        description: "Flattens system connection flags, security verification states, and underlying group infrastructure maps into a small bitmask signature framework.",
        example: `<span class="keyword">local</span> propsBuffer = Rawmeleon.GetPlayerPropertiesRaw(player)`,
        params: [
            { name: "player", type: "Player", desc: "Target player configuration instance." }
        ]
    },
    {
        category: "Environment Telemetry",
        id: "GetPlayerCharacterRaw",
        signature: "Rawmeleon.GetPlayerCharacterRaw(player)",
        description: "Compiles human-simulation frames into a static 48-byte update allocation window. Tracks current Health values, operational limits, Walkspeed physics constraints, instant LinearVelocity changes, and look vector angles.",
        example: `<span class="keyword">local</span> charBuffer = Rawmeleon.GetPlayerCharacterRaw(player)`,
        params: [
            { name: "player", type: "Player", desc: "The player whose active character is being scanned." }
        ]
    },
    {
        category: "Environment Telemetry",
        id: "GetScriptRawData",
        signature: "Rawmeleon.GetScriptRawData(targetScript)",
        description: "Extracts class layout markers and active system execution values belonging to a running Lua source object without creating exposed plain-text context strings in processing storage.",
        example: `<span class="keyword">local</span> scriptBuffer = Rawmeleon.GetScriptRawData(script)`,
        params: [
            { name: "targetScript", type: "Instance", desc: "The LocalScript, Script, or ModuleScript instance." }
        ]
    },
    {
        category: "Environment Telemetry",
        id: "ReturnScriptRawData",
        signature: "Rawmeleon.ReturnScriptRawData(b)",
        description: "Translates an encoded script metadata buffer into a diagnostic reference mapping matrix.",
        example: `<span class="keyword">local</span> scriptInfo = Rawmeleon.ReturnScriptRawData(scriptBuffer)`,
        params: [
            { name: "b", type: "buffer", desc: "The script metadata buffer block." }
        ]
    },
        {
        category: "Network Architecture",
        id: "GetRemoteFunctionRaw",
        signature: "Rawmeleon.GetRemoteFunctionRaw(remoteFunc)",
        description: "Packs structural definitions from a RemoteFunction instance, cataloging if any execution callbacks are linked to its internal invocation routing channel.",
        example: `<span class="keyword">local</span> rfBuffer = Rawmeleon.GetRemoteFunctionRaw(game.ReplicatedStorage.GetItems)`,
        params: [
            { name: "remoteFunc", type: "RemoteFunction", desc: "The target function remote object to profile." }
        ]
    },
    {
        category: "Network Architecture",
        id: "GetRemoteEventRaw",
        signature: "Rawmeleon.GetRemoteEventRaw(remoteEvent)",
        description: "Transforms a RemoteEvent network identity and structural name into an unreadable localized data layout packet.",
        example: `<span class="keyword">local</span> reBuffer = Rawmeleon.GetRemoteEventRaw(game.ReplicatedStorage.NotifyPlayer)`,
        params: [
            { name: "remoteEvent", type: "RemoteEvent", desc: "The target event remote object to analyze." }
        ]
    },
    {
        category: "Network Architecture",
        id: "ReturnRawRemotes",
        signature: "Rawmeleon.ReturnRawRemotes(b, isFunction)",
        description: "Acts as an asymmetrical pipeline reader, extracting structural data elements from either event or function network descriptors using a control toggle check.",
        example: `<span class="keyword">local</span> remoteInfo = Rawmeleon.ReturnRawRemotes(reBuffer, <span class="keyword">false</span>)`,
        params: [
            { name: "b", type: "buffer", desc: "The raw remote packet data block." },
            { name: "isFunction", type: "boolean", desc: "True if decoding a RemoteFunction, false if a RemoteEvent." }
        ]
    },
    {
        category: "Network Architecture",
        id: "GetServiceRawData",
        signature: "Rawmeleon.GetServiceRawData(serviceName)",
        description: "Validates and encapsulates internal engine service calls (e.g., 'TweenService', 'HttpService') into abstract bit sequences to mask diagnostic service tracking checks.",
        example: `<span class="keyword">local</span> serviceBuffer = Rawmeleon.GetServiceRawData(<span class="string">"HttpService"</span>)`,
        params: [
            { name: "serviceName", type: "string", desc: "The text string name of the target service." }
        ]
    },
    {
        category: "Dynamic Layers",
        id: "BlockData",
        signature: "Rawmeleon.BlockData(b, key)",
        description: "Iterates over an allocated buffer array, applying a rolling bitwise XOR cipher across all byte offsets to dynamically mask data markers against scanning scanners.",
        example: `<span class="keyword">local</span> securePacket = Rawmeleon.BlockData(packet, <span class="number">182</span>)`,
        params: [
            { name: "b", type: "buffer", desc: "The target raw packet buffer to protect." },
            { name: "key", type: "number", desc: "XOR cipher mask token (an integer ranging from 0-255)." }
        ]
    },
    {
        category: "Dynamic Layers",
        id: "UnBlockData",
        signature: "Rawmeleon.UnBlockData(b, key)",
        description: "Reverses the XOR operation sequence by processing the altered stream with the matching cipher token layout.",
        example: `<span class="keyword">local</span> plainPacket = Rawmeleon.UnBlockData(securePacket, <span class="number">182</span>)`,
        params: [
            { name: "b", type: "buffer", desc: "The obfuscated cipher data buffer stream." },
            { name: "key", type: "number", desc: "The matching numeric mask key token used to encode it." }
        ]
    },
    {
        category: "Dynamic Layers",
        id: "PackDynamic",
        signature: "Rawmeleon.PackDynamic(dataLayout, ...)",
        description: "Calculates memory metrics for a variable sequence, matches configurations dynamically, and bundles them into an aligned byte structure frame.",
        example: `<span class="keyword">local</span> mixed = Rawmeleon.PackDynamic({<span class="string">"string"</span>, <span class="string">"f32"</span>, <span class="string">"u8"</span>}, <span class="string">"Aimbot"</span>, <span class="number">1.25</span>, <span class="number">0</span>)`,
        params: [
            { name: "dataLayout", type: "table", desc: "An ordered array of data tokens (e.g. 'u8', 'u16', 'f32', 'f64', 'string')." },
            { name: "...", type: "variant", desc: "The tuple stream of items matching the exact dataLayout format order." }
        ]
    },
    {
        category: "Dynamic Layers",
        id: "GetTableRawData",
        signature: "Rawmeleon.GetTableRawData(targetTable)",
        description: "Iterates through standard index-based arrays, runs runtime inspection tracking on elements, maps integer resolutions vs float values automatically, and outputs optimized byte sequences.",
        example: `<span class="keyword">local</span> arrayBuffer = Rawmeleon.GetTableRawData({<span class="number">255</span>, <span class="string">"Stealth"</span>, <span class="keyword">true</span>})`,
        params: [
            { name: "targetTable", type: "table", desc: "Standard array index table holding strings, booleans, or numbers." }
        ]
    }


];

// UI Engine: Renders everything cleanly to index.html on load
function renderDocs() {
    const sidebar = document.getElementById("sidebar-links");
    const container = document.getElementById("docs-container");
    let currentCategory = "";

    documentationData.forEach(item => {
        // Create Sidebar Category Titles dynamically
        if (item.category !== currentCategory) {
            currentCategory = item.category;
            const catHeader = document.createElement("li");
            catHeader.className = "section-title";
            catHeader.innerText = currentCategory;
            sidebar.appendChild(catHeader);
        }

        // Add link to sidebar
        const li = document.createElement("li");
        li.innerHTML = `<a href="#${item.id}">.${item.id}</a>`;
        sidebar.appendChild(li);

        // Generate the documentation block card layout
        let tableRows = "";
        if (item.params && item.params.length > 0) {
            tableRows = `
                <table>
                    <thead><tr><th>Field / Param</th><th>Type</th><th>Description</th></tr></thead>
                    <tbody>
                        ${item.params.map(p => `<tr><td class="name">${p.name}</td><td class="type">${p.type}</td><td>${p.desc}</td></tr>`).join("")}
                    </tbody>
                </table>`;
        }

        const card = document.createElement("div");
        card.className = "api-card";
        card.id = item.id;
        card.innerHTML = `
            <div class="api-header"><div class="api-signature">${item.signature}</div></div>
            <div class="api-body">
                <p class="api-description">${item.description}</p>
                ${tableRows}
                <pre>${item.example}</pre>
            </div>
        `;
        container.appendChild(card);
    });
}


// Native Clipboard Copy Engine
function copyLoadstring() {
    const rawLua = 'local RawmeleonInstaller = loadstring(game:HttpGet("https://raw.githubusercontent.com/CoolDolphim/Rawmeleon-Library/refs/heads/main/LUAModule/SRC.luau"))()';
    
    navigator.clipboard.writeText(rawLua).then(() => {
        const btn = document.getElementById("copy-btn");
        
        // Visual indicator switch to confirm successful capture
        btn.style.color = "var(--accent-green)";
        btn.style.borderColor = "var(--accent-green)";
        btn.style.background = "#1f242c";
        
        setTimeout(() => {
            btn.style.color = "var(--text-main)";
            btn.style.borderColor = "var(--border-color)";
            btn.style.background = "#21262d";
        }, 1200);
    }).catch(err => {
        console.error("Failed to copy source pipeline text: ", err);
    });
}

document.addEventListener("DOMContentLoaded", renderDocs);
